title: Rotsen Acob
email: acob.rotsen@hotmail.com
description: Web developer, self-proclaimed introvert and UNIX enthusiast.
twitter_username: acobrotsen
github_username:  webdevsuperfast

# Build settings
markdown: kramdown
theme: minima

sass:
  load_paths:
    - _sass
    - node_modules

exclude: []