title: Rotsen Acob
email: acob.rotsen@hotmail.com
description: Web developer, self-proclaimed introvert and UNIX enthusiast.
twitter_username: acobrotsen
github_username:  webdevsuperfast
page_background: 'assets/images/carlos-muza-84523-unsplash.jpg'

# Build settings
markdown: kramdown

# Excludes
exclude: [
  'node_modules',
  'gulpfile.js',
  'package.json',
  '_sass',
  '_js',
  '.sass-cache',
  'temp'
]
collections:
  portfolio:
    output: false

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-avatar