title: Rotsen Acob
email: acob.rotsen@hotmail.com
description: Web developer, self-proclaimed introvert and UNIX enthusiast.
twitter_username: acobrotsen
github_username:  webdevsuperfast

# Build settings
markdown: kramdown
exclude: [
  'node_modules',
  'gulpfile.babel.js',
  'package.json',
  '_sass',
  '_js',
  '.sass-cache'
]